---
- name: Copy file from local to remote clients
  hosts: all
  tasks:
  - name: Copy file
    become: true
    copy:
      src: /home/jameswalker/rm_amz_workspaces.sh
      dest: /root/rm_amz_workspaces.sh
      mode: 0755
      owner: root
      group: root


