---
- name: Find a process and kill it
  hosts: all
  tasks:
    - name: Find a process
      ignore_errors: yes
      shell: "ps -few | grep top | grep -v grep | awk '{print $2}'"
      register: running_process


    - name: Kill the process
      ignore_errors: yes
      shell: "kill  {{ item }}"
      with_items: "{{ running_process.stdout_lines }}"
